name: build-and-test

on:
    workflow_dispatch:

jobs:
    build_and_test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: setup
              uses: actions/setup-python@v3
              with:
                python-version: 3.12
            
            - name: install
              run: |
                python -m pip install --upgrade pip
                pip install pytest

            - name: test
              run: |
                ls
                pytest -v tests/
